<?php

// @codingStandardsIgnoreFile

?>
<form class="form support-ticket-reply"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="support-ticket-reply-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <h2 class="support-ticket-reply-title"><?= $block->escapeHtmlAttr(__('Reply')) ?></h2>
    <fieldset class="fieldset">
        <div class="field body required">
            <label class="label" for="body"><span><?= $block->escapeHtml(__('Your Message')) ?></span></label>
            <div class="control">
                <textarea name="body" id="body" title="<?= $block->escapeHtmlAttr(__('Your Message')) ?>" class="input-text" cols="10" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
